### ISSUE TITLE
missing required parameter

### ISSUE THREAD

**Issue by davidjirovec** [timeseriesadmin/timeseriesadmin#1]
I am trying to connect to my db hosted at corlysis.com but I get
```
...
"response": {
  "data": "error\n\"missing required parameter \"\"q\"\"\"\n",
  "status": 400,
...
```

**Comment by jmarceli** [comment]
Did you provide some query in "Query" textarea? This is a limitation at least for now. You have to execute some query to test the connection, it might be something as simple as `show databases`.

If that is not the case please check the Explorer panel. Does it work?

**Comment by davidjirovec** [comment]
Yes I did provide query. I also tried running influx instance locally and I did not have issues with Time Series Admin.

I guess it might be something specific to database hosted on Corlysis. Could you maybe try to create account there and try to connect yourself? Don't worry the basic tier is free ;)

Regarding Explorer panel - this is the place where I got the error. it shows "ERROR. CHECK DETAILS." and when I click it, there is json containing details which also contains the parted I've posted originally.

**Comment by jmarceli** [comment]
Hi, I've reproduced your problem and unfortunately there is no easy fix for that.

Corlysis DBs doesn't support executing queries through POST request and doesn't respect results format CSV header described in [Influx API](https://docs.influxdata.com/influxdb/v1.7/tools/api/#options) and because of that, Time Series Admin is unable to query and parse the results.

I may address both issues later on but there is no quick fix for now.
