### ISSUE TITLE
Add possibility to query InfluxDB using Flux queries

### ISSUE THREAD

**Issue by Mariushrek** [timeseriesadmin/timeseriesadmin#553]
Hey!

Thank you for this software - Your application has improved my querying of many databases ;)

I have a question and feature request - can you add a possibility to query Influx using FLUX queries?
It can help my Team with more complicated queries in the same user-friendy way ;)

Thanks,
Mariusz Kuras

**Comment by Mariushrek** [comment]
Ping ;)

**Comment by jmarceli** [comment]
Hi @Mariushrek  thanks for your interest in this project. Please let me know if you have tried Chronograf (https://github.com/influxdata/chronograf)? I'm eager to know because as far as I'm aware Chronograf is fairly complete software that supports Flux and because of that I don't see much value in further development of the Timeseriesadmin.
